In [8]:
import cv2 as cv2
import numpy as np

im = np.array([[0,0,0,0,0],
               [0,0,0,0,0],
               [1,1,0,0,0],
               [1,1,0,1,0],
               [0,0,0,0,0]],dtype="uint8")
k = np.array([[-1,-1,-1],
              [ 0, 1,-1],
              [ 0, 0,-1]])

out = cv2.morphologyEx(im, cv2.MORPH_HITMISS, k)
print(out)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]


In [3]:
input_image = np.array((
    [0, 0, 0, 0, 0, 0, 0, 0],
    [0, 255, 255, 255, 0, 0, 0, 255],
    [0, 255, 255, 255, 0, 0, 0, 0],
    [0, 255, 255, 255, 0, 255, 0, 0],
    [0, 0, 255, 0, 0, 0, 0, 0],
    [0, 0, 255, 0, 0, 255, 255, 0],
    [0,255, 0, 255, 0, 0, 255, 0],
    [0, 255, 255, 255, 0, 0, 0, 0]), dtype="uint8")
kernel = np.array((
        [0, 1, 0],
        [1, -1, 1],
        [0, 1, 0]), dtype="int")
out = cv2.morphologyEx(input_image, cv2.MORPH_HITMISS, kernel)
print(out)

[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]
 [  0   0 255   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0]]
